language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
    - secure: TyKZf2Gn7ucSHNWYgjWtMEHPjlvNKw6/ST4n28zV2kAYnDX1pJdGfbM0DzhMAB1taFBhAr16qQefApnNFJQLu4e65ovXXglFxd7Do/bofnmaSBln0edG05Hg0/yn7mmNY0NwbKVC4qX2OJZiwqvcjhBTh54J4W3ATUycNhPQDOs=

repos:
  XRAN: http://yihui.name/xran

before_install:
  - "wget -q http://yihui.name/xran/.gitconfig -O ~/.gitconfig"

after_success:
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
